name: LaTeX build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run latexmk
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: main.tex
          args: -interaction=nonstopmode -shell-escape
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: main.pdf
          path: main.pdf
